[project]
name = "lego"
version = "0.1.0"
requires-python = ">=3.14"
dependencies=[
    "alembic>=1.19.2",
    "asyncpg>=0.31.0",
    "bcrypt>=5.0.0",
    "biopython>=1.88",
    "fastapi>=0.141.1",
    "pydantic-settings>=2.15.0",
    "pydantic[email]>=2.13.5",
    "pyjwt>=2.13.0",
    "redis>=8.1.0",
    "ruff>=0.16.6",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
]
